### ISSUE TITLE
Just thanks

### ISSUE THREAD

**Issue by eleazarherrera** [NeleB54Gold/CocktailsInfoBot#1]
Hi thanks for the bot. I have been testing it and I have made a short review on my Youtube channel because of the interesting bot. Here is the link https://youtube.com/shorts/LI2-3zdg6rw?feature=share

I would like you to add more IBA recipes and mention the category to which they correspond.

Thanks

**Comment by NeleB54Gold** [comment]
Hi, thanks for the review, but this is the place for the issues, if you want to talk to me contact @NeleBotsSupporter on Telegram.
